# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\python code\Camera_esp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QThread, pyqtSignal,Qt
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QLCDNumber
from datetime import datetime
from Map1 import Ui_MainWindow
import cv2

class Ui_Camerade(object):
    def open_location(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Camerade):
        Camerade.setObjectName("Camerade")
        Camerade.resize(1525, 730)
        Camerade.setStyleSheet("QWidget#centralwidget{background-color: rgb(17, 17, 17);}")
        self.centralwidget = QtWidgets.QWidget(Camerade)
        self.centralwidget.setStyleSheet("background-color:rgb(26, 26, 26)")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 90, 640, 480))
        self.label.setStyleSheet("background-color: rgb(255,255,255);")
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 580, 191, 51))
        font = QtGui.QFont()
        font.setItalic(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("broder-radius:100px;\n"
"background-color:rgb(0,128,0);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 580, 201, 51))
        self.pushButton_2.setStyleSheet("broder-radius:100px;\n"
"background-color:rgb(128,0,0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 580, 211, 51))
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("\n"
"broder-radius:200000px;\n"
"background-color:rgb(50,50,50);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 561, 41))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(690, 60, 111, 51))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(690, 140, 111, 41))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(690, 270, 111, 51))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setGeometry(QtCore.QRect(690, 210, 111, 41))
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setGeometry(QtCore.QRect(690, 450, 121, 41))
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setGeometry(QtCore.QRect(700, 350, 111, 51))
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_7.setGeometry(QtCore.QRect(690, 590, 121, 41))
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_8.setGeometry(QtCore.QRect(690, 520, 121, 41))
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(1220, 210, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1020, 580, 181, 71))
        self.pushButton_4.setStyleSheet("broder-radius:100px;\n"
"background-color:rgb(0,128,0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1290, 580, 171, 71))
        self.pushButton_5.setStyleSheet("broder-radius:200px;\n"
"background-color:rgb(50,50,50);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda : self.open_location())
        self.pushButton_6.setGeometry(QtCore.QRect(1200, 20, 151, 61))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(6, 47, 91);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.dial = QtWidgets.QDial(self.centralwidget)
        #change value
        self.dial.valueChanged.connect(lambda : self.dialer())
        self.dial.setGeometry(QtCore.QRect(850, 60, 50, 64))
        self.dial.setStyleSheet("QDial{\n"
"qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147))\n"
"\n"
"}")
        self.dial.setObjectName("dial")
        self.dial_2 = QtWidgets.QDial(self.centralwidget)
        # change value
        self.dial_2.valueChanged.connect(lambda: self.dialer2())
        self.dial_2.setGeometry(QtCore.QRect(850, 130, 50, 64))
        self.dial_2.setObjectName("dial_2")
        self.dial_3 = QtWidgets.QDial(self.centralwidget)
        # change value
        self.dial_3.valueChanged.connect(lambda: self.dialer3())
        self.dial_3.setGeometry(QtCore.QRect(850, 200, 50, 64))
        self.dial_3.setObjectName("dial_3")
        self.dial_4 = QtWidgets.QDial(self.centralwidget)
        # change value
        self.dial_4.valueChanged.connect(lambda: self.dialer4())
        self.dial_4.setGeometry(QtCore.QRect(850, 270, 50, 64))
        self.dial_4.setObjectName("dial_4")
        self.dial_5 = QtWidgets.QDial(self.centralwidget)
        # change value
        self.dial_5.valueChanged.connect(lambda: self.dialer5())
        self.dial_5.setGeometry(QtCore.QRect(850, 340, 50, 64))
        self.dial_5.setObjectName("dial_5")
        self.dial_6 = QtWidgets.QDial(self.centralwidget)
        # change value
        self.dial_6.valueChanged.connect(lambda: self.dialer6())
        self.dial_6.setGeometry(QtCore.QRect(850, 430, 50, 64))
        self.dial_6.setObjectName("dial_6")
        self.dial_7 = QtWidgets.QDial(self.centralwidget)
        # change value
        self.dial_7.valueChanged.connect(lambda: self.dialer7())
        self.dial_7.setGeometry(QtCore.QRect(850, 510, 50, 64))
        self.dial_7.setObjectName("dial_7")
        self.dial_8 = QtWidgets.QDial(self.centralwidget)
        # change value
        self.dial_8.valueChanged.connect(lambda: self.dialer8())
        self.dial_8.setGeometry(QtCore.QRect(850, 580, 50, 64))
        self.dial_8.setObjectName("dial_8")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_9.setGeometry(QtCore.QRect(1010, 430, 441, 121))
        self.lcdNumber_9.setStyleSheet("QLCDNumber{\n"
"background-color: darkgreen;\n"
"\n"
"}")
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.lcdNumber_10 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_10.setGeometry(QtCore.QRect(980, 110, 491, 81))
        self.lcdNumber_10.setStyleSheet("QLCDNumber{\n"
"background-color: darkgreen;\n"
"\n"
"}")
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        Camerade.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Camerade)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1525, 25))
        self.menubar.setObjectName("menubar")
        self.menuDark_mode = QtWidgets.QMenu(self.menubar)
        self.menuDark_mode.setObjectName("menuDark_mode")
        Camerade.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Camerade)
        self.statusbar.setObjectName("statusbar")

        self.pushButton.clicked.connect(self.start_video)
        self.pushButton_2.clicked.connect(self.cancel)
        self.pushButton_3.clicked.connect(self.exitt)
        Camerade.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuDark_mode.menuAction())

        self.minute = 0
        self.second = 0
        self.startwatch = False

        self.pushButton_4.clicked.connect(self.Start)
        self.pushButton_5.clicked.connect(self.Reset)

        #create timer1
        self.timer1 = QTimer()
        self.timer1.timeout.connect(self.lcd_number)

        self.timer1.start(1000)
        self.lcd_number()

        # Create A Timer
        self.timer = QTimer()
        self.timer.timeout.connect(self.show_counter)

        self.timer.start(1000)

        self.retranslateUi(Camerade)
        QtCore.QMetaObject.connectSlotsByName(Camerade)

    def lcd_number(self):
        time =datetime.now()
        formatted_time=time.strftime("%I :%M :%S %p")
        self.lcdNumber_10.setDigitCount(12)
        self.lcdNumber_10.setSegmentStyle(QLCDNumber.Flat)
        self.lcdNumber_10.display(formatted_time)

    def dialer(self):
        #grab the current
        value = self.dial.value()
        self.lcdNumber.display(str(value))

    def dialer2(self):
        #grab the current
        value2 = str(self.dial_2.value())
        self.lcdNumber_2.display(value2)

    def dialer3(self):
        #grab the current
        value3 = str(self.dial_3.value())
        self.lcdNumber_4.display(value3)

    def dialer4(self):
        #grab the current
        value4 = str(self.dial_4.value())
        self.lcdNumber_3.display(value4)

    def dialer5(self):
        #grab the current
        value5 = str(self.dial_5.value())
        self.lcdNumber_6.display(value5)

    def dialer6(self):
        #grab the current
        value6 = str(self.dial_6.value())
        self.lcdNumber_5.display(value6)

    def dialer7(self):
        #grab the current
        value7 = str(self.dial_7.value())
        self.lcdNumber_8.display(value7)

    def dialer8(self):
        #grab the current
        value8 = str(self.dial_8.value())
        self.lcdNumber_7.display(value8)

    def show_counter(self):
        if self.startwatch:
            self.second += 1
            if (self.second == 60):
                self.minute += 1
                self.second = 0

        text = str(self.minute) + ":" + str(self.second)
        self.lcdNumber_9.setDigitCount(12)
        self.lcdNumber_9.setSegmentStyle(QLCDNumber.Flat)
        self.lcdNumber_9.display(text)

    def Start(self):
        if self.pushButton_4.text() == "Stop":
            self.pushButton_4.setText("Resume")
            self.startwatch = False
            self.pushButton_4.setStyleSheet("broder-radius:100px;\n"
                                                "background-color:rgb(128,0,0);\n"
                                                "")
        else:
            self.startwatch = True
            self.pushButton_4.setText("Stop")
            self.pushButton_4.setStyleSheet("broder-radius:100px;\n"
                                                "background-color:rgb(0,128,0);")

    def Reset(self):
        self.minute = 0
        self.second = 0

    def start_video(self):
        self.Work = Work()
        self.Work.start()
        self.Work.Imageupd.connect(self.Imageupd_slot)

    def Imageupd_slot(self,Image):
        self.label.setPixmap(QPixmap.fromImage(Image))

    def cancel(self):
        self.Work.stop()

    def exitt(self):
        sys.exit()

    def retranslateUi(self, Camerade):
        _translate = QtCore.QCoreApplication.translate
        Camerade.setWindowTitle(_translate("Camerade", "MainWindow"))
        self.pushButton.setText(_translate("Camerade", "Start"))
        self.pushButton_2.setText(_translate("Camerade", "Stop"))
        self.pushButton_3.setText(_translate("Camerade", "Exit"))
        self.pushButton_4.setText(_translate("Camerade", "Start time"))
        self.pushButton_5.setText(_translate("Camerade", "Reset"))
        self.pushButton_6.setText(_translate("Camerade", "Map / location"))
        self.menuDark_mode.setTitle(_translate("Camerade", "Dark mode"))

class Work(QThread):
    Imageupd = pyqtSignal(QImage)
    def run(self):
        self.hillo =True
        cap = cv2.VideoCapture(0)
        while self.hillo:
            ret , frame= cap.read()
            if ret:
                Image = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
                flip = cv2.flip(Image,1)
                convert= QImage(flip.data, flip.shape[1],flip.shape[0],QImage.Format_RGB888)
                pic=convert.scaled(640,480,Qt.KeepAspectRatio)
                self.Imageupd.emit(pic)
    def stop(self):
        self.hillo=False
     #   self.quit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Camerade = QtWidgets.QMainWindow()
    ui = Ui_Camerade()
    ui.setupUi(Camerade)
    Camerade.show()
    sys.exit(app.exec_())
